<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  exclude-result-prefixes="sitemap">

  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html>
    <head>
      <title>XML Sitemap</title>
      <style type="text/css">
        body {
          font-family: "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
          background-color: #f9f9f9;
          margin: 0;
          padding: 2em;
        }
        h1 {
          background: #4285f4;
          color: white;
          padding: 1em;
          margin-top: 0;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 1em;
        }
        th, td {
          padding: 0.75em;
          border-bottom: 1px solid #ccc;
          text-align: left;
        }
        th {
          background-color: #eaeaea;
        }
        .footer {
          margin-top: 2em;
          font-size: 0.9em;
          color: #666;
        }
        .footer a {
          color: #4285f4;
          text-decoration: none;
        }
      </style>
    </head>
    <body>
      <h1>XML Sitemap</h1>
      <table>
        <tr>
          <th>URL</th>
          <th>Last Modified</th>
          <th>Change Frequency</th>
          <th>Priority</th>
        </tr>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <tr>
            <td>
              <a href="{sitemap:loc}">
                <xsl:value-of select="sitemap:loc"/>
              </a>
            </td>
            <td><xsl:value-of select="sitemap:lastmod"/></td>
            <td><xsl:value-of select="sitemap:changefreq"/></td>
            <td><xsl:value-of select="sitemap:priority"/></td>
          </tr>
        </xsl:for-each>
      </table>

      <div class="footer">
        Sitemap generated by SEOToolkit plugin: Developed by 
        <a href="https://gravdeveloper.com/" target="_blank">https://gravdeveloper.com/</a>
      </div>
    </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
